"""Data models for palimpsest. See docs/05-data-schema.md."""

from app.models.api import (
    ERROR_STATUS,
    ERROR_TITLE,
    CapabilitiesResponse,
    ComparisonAccepted,
    ComparisonStatus,
    CreateComparisonRequest,
    ErrorCode,
    HealthResponse,
    ParserCapabilitiesResponse,
    ProblemDetail,
)
from app.models.diff import (
    BlockMetrics,
    BlockPage,
    BlockStatus,
    ComparisonResult,
    DiffBlock,
    DiffMetrics,
    DiffOptions,
    Granularity,
    Token,
    TokenStatus,
)
from app.models.document import (
    Block,
    BlockKind,
    BoundingBox,
    Document,
    DocumentMetadata,
    DocumentSummary,
    IngestionWarning,
    SourceFormat,
)
from app.models.identifiers import (
    block_id,
    diff_block_id,
    group_id,
    new_comparison_id,
    new_document_id,
)
from app.models.invariants import (
    InvariantViolation,
    assert_comparison,
    assert_reconstructs,
    check_block,
    check_comparison,
)

__all__ = [
    "ERROR_STATUS",
    "ERROR_TITLE",
    "Block",
    "BlockKind",
    "BlockMetrics",
    "BlockPage",
    "BlockStatus",
    "BoundingBox",
    "CapabilitiesResponse",
    "ComparisonAccepted",
    "ComparisonResult",
    "ComparisonStatus",
    "CreateComparisonRequest",
    "DiffBlock",
    "DiffMetrics",
    "DiffOptions",
    "Document",
    "DocumentMetadata",
    "DocumentSummary",
    "ErrorCode",
    "Granularity",
    "HealthResponse",
    "IngestionWarning",
    "InvariantViolation",
    "ParserCapabilitiesResponse",
    "ProblemDetail",
    "SourceFormat",
    "Token",
    "TokenStatus",
    "assert_comparison",
    "assert_reconstructs",
    "block_id",
    "check_block",
    "check_comparison",
    "diff_block_id",
    "group_id",
    "new_comparison_id",
    "new_document_id",
]
