/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description Describe what this server can parse, and its current limits.
         *
         *     The client builds its upload accept list from this rather than hardcoding
         *     formats, which is what makes registering the OCR parser later a
         *     zero-frontend-change event.
         */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Comparison
         * @description Collate two witnesses.
         *
         *     Phase 1 always computes inline and returns ``201``. The ``202
         *     ComparisonAccepted`` path for oversize manuscripts is phase 5; the response
         *     model already exists so enabling it is a routing change, not a schema
         *     change.
         */
        post: operations["create_comparison_api_v1_comparisons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparisons/{comparison_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comparison */
        get: operations["get_comparison_api_v1_comparisons__comparison_id__get"];
        put?: never;
        post?: never;
        /** Delete Comparison */
        delete: operations["delete_comparison_api_v1_comparisons__comparison_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comparisons/{comparison_id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comparison Blocks */
        get: operations["get_comparison_blocks_api_v1_comparisons__comparison_id__blocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Block
         * @description The atomic unit of alignment: a paragraph, heading, or verse line.
         */
        Block: {
            /** Id */
            id: string;
            /** Index */
            index: number;
            kind: components["schemas"]["BlockKind"];
            /** Text */
            text: string;
            /** Style */
            style?: string | null;
            /** Page */
            page?: number | null;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Confidence */
            confidence?: number | null;
            bbox?: components["schemas"]["BoundingBox"] | null;
        };
        /**
         * BlockKind
         * @description What a block is, structurally.
         * @enum {string}
         */
        BlockKind: "PARAGRAPH" | "HEADING" | "VERSE_LINE" | "QUOTE" | "LIST_ITEM" | "ARTIFACT";
        /** BlockMetrics */
        BlockMetrics: {
            /** Similarity */
            similarity: number;
            /** Edit Count */
            edit_count: number;
            /** Insertions */
            insertions: number;
            /** Deletions */
            deletions: number;
            /** Churn */
            churn: number;
        };
        /**
         * BlockPage
         * @description A window into a comparison's blocks, for very long manuscripts.
         */
        BlockPage: {
            /** Blocks */
            blocks: components["schemas"]["DiffBlock"][];
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Total Blocks */
            total_blocks: number;
        };
        /**
         * BlockStatus
         * @description How a block relates to its counterpart in the other witness.
         * @enum {string}
         */
        BlockStatus: "UNCHANGED" | "MODIFIED" | "INSERTED" | "DELETED" | "MOVED" | "SPLIT" | "MERGED";
        /** Body_upload_document_api_v1_documents_post */
        Body_upload_document_api_v1_documents_post: {
            /** File */
            file: string;
            /** Title */
            title?: string | null;
        };
        /**
         * BoundingBox
         * @description Position of a block on a source page. Reserved for OCR.
         */
        BoundingBox: {
            /** Page */
            page: number;
            /** X0 */
            x0: number;
            /** Y0 */
            y0: number;
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
        };
        /**
         * CapabilitiesResponse
         * @description What this server can parse, and its current limits.
         *
         *     The client builds its upload accept list from this rather than hardcoding
         *     formats, which is what makes registering the OCR parser later a
         *     zero-frontend-change event.
         */
        CapabilitiesResponse: {
            /** Parsers */
            parsers: components["schemas"]["ParserCapabilitiesResponse"][];
            /** Max Upload Bytes */
            max_upload_bytes: number;
            /** Max Blocks Per Comparison */
            max_blocks_per_comparison: number;
            /** Max Tokens Per Comparison */
            max_tokens_per_comparison: number;
            /** Default Block Page Limit */
            default_block_page_limit: number;
            /** Max Block Page Limit */
            max_block_page_limit: number;
            diff_options_defaults: components["schemas"]["DiffOptions"];
        };
        /**
         * ComparisonResult
         * @description The complete collation of two witnesses.
         */
        ComparisonResult: {
            /** Comparison Id */
            comparison_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            a: components["schemas"]["DocumentSummary"];
            b: components["schemas"]["DocumentSummary"];
            /** Blocks */
            blocks: components["schemas"]["DiffBlock"][];
            metrics: components["schemas"]["DiffMetrics"];
            options: components["schemas"]["DiffOptions"];
            /** Truncated */
            truncated: boolean;
            /** Total Blocks */
            total_blocks: number;
        };
        /** CreateComparisonRequest */
        CreateComparisonRequest: {
            /** A Document Id */
            a_document_id: string;
            /** B Document Id */
            b_document_id: string;
            options?: components["schemas"]["DiffOptions"];
        };
        /**
         * DiffBlock
         * @description One block of the collation, carrying all three token streams.
         *
         *     Response-shaped: every field is always emitted, so none carry defaults.
         *     A field with a default is *not required* in the generated OpenAPI schema,
         *     which would force every client to null-check values that are in fact
         *     always present.
         */
        DiffBlock: {
            /** Id */
            id: string;
            status: components["schemas"]["BlockStatus"];
            kind: components["schemas"]["BlockKind"];
            /** A Index */
            a_index: number | null;
            /** B Index */
            b_index: number | null;
            /** A Block Id */
            a_block_id: string | null;
            /** B Block Id */
            b_block_id: string | null;
            /** Tokens */
            tokens: components["schemas"]["Token"][];
            /** A Tokens */
            a_tokens: components["schemas"]["Token"][];
            /** B Tokens */
            b_tokens: components["schemas"]["Token"][];
            metrics: components["schemas"]["BlockMetrics"];
            /** Move Distance */
            move_distance: number | null;
            /** Group Id */
            group_id: string | null;
        };
        /** DiffMetrics */
        DiffMetrics: {
            /** Similarity */
            similarity: number;
            /** Edit Count */
            edit_count: number;
            /** Insertions */
            insertions: number;
            /** Deletions */
            deletions: number;
            /** Unchanged Tokens */
            unchanged_tokens: number;
            /** Churn */
            churn: number;
            /** Blocks Moved */
            blocks_moved: number;
            /** Blocks Split */
            blocks_split: number;
            /** Blocks Merged */
            blocks_merged: number;
            /** A Word Count */
            a_word_count: number;
            /** B Word Count */
            b_word_count: number;
        };
        /** DiffOptions */
        DiffOptions: {
            /** @default WORD */
            granularity: components["schemas"]["Granularity"];
            /**
             * Detect Moves
             * @default true
             */
            detect_moves: boolean;
            /**
             * Align Threshold
             * @default 0.5
             */
            align_threshold: number;
            /**
             * Move Threshold
             * @default 0.75
             */
            move_threshold: number;
            /**
             * Ignore Case
             * @default false
             */
            ignore_case: boolean;
            /**
             * Ignore Punctuation
             * @default false
             */
            ignore_punctuation: boolean;
            /**
             * Normalize Whitespace
             * @default true
             */
            normalize_whitespace: boolean;
        };
        /**
         * Document
         * @description One parsed witness.
         */
        Document: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            source_format: components["schemas"]["SourceFormat"];
            /** Blocks */
            blocks: components["schemas"]["Block"][];
            metadata: components["schemas"]["DocumentMetadata"];
            /** Warnings */
            warnings?: components["schemas"]["IngestionWarning"][];
        };
        /** DocumentMetadata */
        DocumentMetadata: {
            /** Word Count */
            word_count: number;
            /** Block Count */
            block_count: number;
            /** Char Count */
            char_count: number;
            /** Detected Language */
            detected_language?: string | null;
            /** Parser Name */
            parser_name: string;
            /** Parser Version */
            parser_version: string;
            /** Ocr Confidence */
            ocr_confidence?: number | null;
        };
        /**
         * DocumentSummary
         * @description A ``Document`` without its blocks.
         *
         *     Embedded in ``ComparisonResult`` so the payload describes both witnesses
         *     without carrying two full copies of the source text alongside the diff.
         */
        DocumentSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            source_format: components["schemas"]["SourceFormat"];
            metadata: components["schemas"]["DocumentMetadata"];
            /** Warnings */
            warnings?: components["schemas"]["IngestionWarning"][];
        };
        /**
         * ErrorCode
         * @description Every error the API can return.
         *
         *     Each maps to one HTTP status via ``ERROR_STATUS``.
         * @enum {string}
         */
        ErrorCode: "UNSUPPORTED_FORMAT" | "FILE_TOO_LARGE" | "MALFORMED_DOCUMENT" | "EMPTY_DOCUMENT" | "DOCUMENT_NOT_FOUND" | "COMPARISON_NOT_FOUND" | "COMPARISON_EXPIRED" | "DIFF_BUDGET_EXCEEDED" | "OCR_REQUIRED" | "RATE_LIMITED" | "INTERNAL_ERROR";
        /**
         * Granularity
         * @enum {string}
         */
        Granularity: "WORD" | "CHARACTER";
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * IngestionWarning
         * @description Something the parser had to guess at, surfaced rather than hidden.
         */
        IngestionWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Block Id */
            block_id?: string | null;
        };
        /** ParserCapabilitiesResponse */
        ParserCapabilitiesResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            source_format: components["schemas"]["SourceFormat"];
            /** Extensions */
            extensions: string[];
            /** Media Types */
            media_types: string[];
            /** Preserves Headings */
            preserves_headings: boolean;
            /** Preserves Page Numbers */
            preserves_page_numbers: boolean;
            /** Is Lossy */
            is_lossy: boolean;
            /** Is Async */
            is_async: boolean;
            /** Requires Network */
            requires_network: boolean;
            /** Emits Confidence */
            emits_confidence: boolean;
            /** Emits Bboxes */
            emits_bboxes: boolean;
        };
        /**
         * ProblemDetail
         * @description RFC 9457 problem detail.
         */
        ProblemDetail: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            code: components["schemas"]["ErrorCode"];
        };
        /**
         * SourceFormat
         * @description The format a witness arrived in.
         *
         *     ``OCR`` is reachable by no parser in v1. It exists now so that activating
         *     the OCR pipeline is not a schema change.
         * @enum {string}
         */
        SourceFormat: "TXT" | "MARKDOWN" | "DOCX" | "PDF" | "OCR";
        /**
         * Token
         * @description A contiguous run of same-status words.
         *
         *     Note this is a *run*, not a single word: ``{"text": "cat sat ", ...}`` is
         *     two words in one object. Emitting one object per word would triple the
         *     payload and produce one DOM node per word for no reader-visible benefit.
         *
         *     The consequence, which is the easiest thing in this schema to get wrong:
         *     every count in ``BlockMetrics`` and ``DiffMetrics`` is a count of **words**,
         *     never a count of ``Token`` objects.
         */
        Token: {
            /** Text */
            text: string;
            status: components["schemas"]["TokenStatus"];
        };
        /**
         * TokenStatus
         * @description What happened to a run of words.
         *
         *     This enum is closed and will not grow. A token either survived, arrived, or
         *     left; anything richer belongs at block level. Keeping it closed is what
         *     allows the client's ``TokenSpan`` to stay trivially fast when a page holds
         *     tens of thousands of them.
         * @enum {string}
         */
        TokenStatus: "UNCHANGED" | "INSERTION" | "DELETION";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    upload_document_api_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_document_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_comparison_api_v1_comparisons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_comparison_api_v1_comparisons__comparison_id__get: {
        parameters: {
            query?: {
                include_blocks?: boolean;
            };
            header?: never;
            path: {
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_comparison_api_v1_comparisons__comparison_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_comparison_blocks_api_v1_comparisons__comparison_id__blocks_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number | null;
            };
            header?: never;
            path: {
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockPage"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Unprocessable content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
